Przegląd produktu na podstronie /product/
odevpl/wdp-2307 pull request #46
Opened 2023-07-13 11:54 UTC by Maciej-Lask

Uprzejmie proszę o nieczepianie się ikonek, bo nie wszystkie dało radę znaleźć

2023-07-13 11:57 UTC, Maciej-Lask commented
Przykładowy link do podstrony produktu
http://localhost:3000/product/4

2023-07-13 17:28 UTC, kachurovskiyp requested changes
Tak że co odnoście wyglądu. Miniaturki za mocno rozciągnięte, Pojawia się puste miejsce pod galerią, co nie jest zgodne z designem. Uważam, że warto rozciągnąć box głównego picture, co wyrówna te niezgodności.
![image](https://github.com/odevpl/wdp-2307/assets/38604336/c47bac7d-8d6c-42e4-a54f-26be72aa04ed)

2023-07-13 17:28 UTC, kachurovskiyp commented on src/components/features/ProductData/ProductData.js
> +  const initialStateId = `aenean-ru-bristique-${productId}`;
Sprawdź routing w App

> <Route exact path={'/product/:productId'} component={ProductPage} />

Masz ":" po sleszu jeszcze. Jak go dopisać, cała strona się sypie.

2023-07-14 16:01 UTC, Maciej-Lask commented on src/components/features/ProductData/ProductData.js
> +  const initialStateId = `aenean-ru-bristique-${productId}`;
To jest parametr product id, tego się nie dopisuje. To jest po to żeby można było zrobić const { productId } = useParams();.
Więc moim zdaniem jest dobrze i powinno być http://localhost:3000/product/4 a nie http://localhost:3000/product/:4

2023-07-15 06:45 UTC, kachurovskiyp approved these changes

2023-07-15 06:45 UTC, merged