WDP-49
odevpl/wdp-2307 pull request #53
Opened 2023-07-14 15:06 UTC by Hylarious

Add adding to and removing form cart functionality with cart bootstrap fix

2023-07-14 15:09 UTC, Hylarious commented
Ważne: jako, że aktualnie nie da się kliknąć 'Add to cart'  na productboxie, polecam sprawdzać na produkcie w promoted

2023-07-15 15:46 UTC, Maciej-Lask requested changes
Generalnie to są dwa błędy jeden mały a drugi taki większy 
1.jak dodasz 3 takie same produkty i naciśniesz x to z koszyka usuwane są wszystkie 3 i moim zdaniem powinien być usuwany tylko jeden mimo że są tego samego typu
2.jak dodasz dwa produkty dwa razy (czasami działa też dla innych ilości) to po usunięciu produktów jeden z nich jest dalej wyświetlany i nie do się go usunąć, to jest zdaje się błąd z wyświetlaniem/odświeżaniem bo w redux store koszyk jest pusty.

https://github.com/odevpl/wdp-2307/assets/65400831/46f5cfa1-f8c6-4b3d-9772-9d5a591f0068

2023-07-15 19:46 UTC, Hylarious commented
Poprawione ^ ^

2023-07-15 20:00 UTC, Maciej-Lask approved these changes

2023-07-15 20:00 UTC, merged